import test from 'node:test';import assert from 'node:assert/strict';
import {ActivityWindow,clipBoxVisible,cameraClipMatrix,ViewActivity,sectorBounds} from '../src/activity-window.js';
import {BotDecisionBudget,bossShouldThink} from '../src/bot-budget.js';
import {busCameraPose,applyBusCamera} from '../src/bus-camera.js';
const I=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const box=(x=0,z=0,r=.2)=>({x0:x-r,x1:x+r,y0:-r,y1:r,z0:z-r,z1:z+r});
test('retention is five seconds, not five rendered frames',()=>{const w=new ActivityWindow();w.touch('a');assert.ok(w.recent('a',5));assert.ok(!w.recent('a',5.001));for(let t=0;t<5;t+=.01){w.advance(t);assert.ok(w.recent('a'));}w.advance(5.1);w.prune();assert.equal(w.last.size,0);});
test('looking again restarts the five-second retention window',()=>{const w=new ActivityWindow();w.touch('a');w.advance(4);w.touch('a');assert.ok(w.recent('a',8.99));assert.ok(!w.recent('a',9.01));});
test('a new round clock reset clears stale residency',()=>{const w=new ActivityWindow();w.advance(100);w.touch('a');w.advance(1);assert.ok(!w.recent('a'));});
test('clip frustum retains a containing box and rejects each outer plane',()=>{assert.ok(clipBoxVisible(I,box()));assert.ok(clipBoxVisible(I,box(0,0,3)));for(const k of ['x','y','z'])for(const sign of [-1,1]){const b=box();b[k+'0']=sign*3-.2;b[k+'1']=sign*3+.2;assert.equal(clipBoxVisible(I,b),false,k+sign);}});
test('crossing a clip plane is conservatively retained',()=>{assert.ok(clipBoxVisible(I,box(.95)));assert.ok(clipBoxVisible(I,box(0,.95)));});
test('invalid or unavailable camera matrices cannot erase the map',()=>{assert.ok(clipBoxVisible(null,box()));assert.ok(clipBoxVisible([...I.slice(0,15),NaN],box(50)));assert.ok(clipBoxVisible(I,{x0:NaN}));});
test('projection/view multiplication preserves camera translation',()=>{const v=[...I];v[12]=-10;const camera={projectionMatrix:{elements:I},matrixWorldInverse:{elements:v},updateMatrixWorld(){}};const m=cameraClipMatrix(camera);assert.ok(clipBoxVisible(m,box(10)));assert.equal(clipBoxVisible(m,box(0)),false);});
test('sector bounds include overhanging tall buildings and never shrink when destroyed',()=>{const s={x:0,z:0,w:96,d:96,buildings:[{x:48,z:0,w:40,d:20,height:190}],obstacles:[]};const b=sectorBounds(s);assert.ok(b.x1>=72);assert.ok(b.y1>=194);s.buildings=[];assert.equal(sectorBounds(s),b);});
test('offscreen chunks stop being needed but survive for five seconds',()=>{let now=0;const a=new ViewActivity(()=>now),camera={position:{x:0,y:0,z:0},projectionMatrix:{elements:I},matrixWorldInverse:{elements:I}};a.begin(camera);assert.ok(a.needed('x',box(0),0));const out=box(50);now=4.99;a.begin(camera);assert.equal(a.needed('x',out,0),false);assert.ok(a.recent('x'));now=5.01;a.begin(camera);assert.equal(a.recent('x'),false);});
test('collision/preload halo remains useful behind the camera',()=>{const a=new ViewActivity(()=>0),camera={position:{x:0,y:0,z:0},projectionMatrix:{elements:I},matrixWorldInverse:{elements:I}};a.begin(camera);assert.equal(a.visible(box(10)),false);assert.ok(a.needed('halo',box(10)));});
function bots(){let calls=0,time=0;const p={id:'bot',bot:true,hp:100,x:700,y:0,z:0,grounded:true,team:2,brain:{}};const human={id:'human',hp:100,x:0,z:0,angle:0,team:1};const a={players:[p,human],projectiles:[],mode:'royale',botEvery:1,botInput(_,dt){calls++;time+=dt;return {x:1,z:0,fire:false};}};return {a,p,human,b:new BotDecisionBudget(),calls:()=>calls,time:()=>time};}
function run(f,seconds){for(let i=0;i<seconds*60;i++){f.b.update(f.a,1/60);f.b.input(f.a,f.p,1/60);}}
test('offscreen isolated bot decisions drop to 2Hz only after grace, timers receive elapsed time',()=>{const f=bots();run(f,5.1);const before=f.calls();run(f,5);assert.ok(f.calls()-before<=11);assert.ok(f.calls()-before>=9);assert.ok(f.time()>9.5);});
test('turning towards a distant bot wakes its decisions promptly',()=>{const f=bots();f.p.x=500;run(f,6);f.human.angle=Math.PI/2;const before=f.calls();run(f,1);assert.ok(f.calls()-before>=30);});
test('nearby threat behind the player is always active',()=>{const f=bots();f.p.x=10;f.p.z=-25;run(f,7);assert.ok(f.calls()>350);});
for(const mode of ['duel','projectile','enemy','airborne','bus','remembered','vehicle'])test('offscreen gameplay remains hot: '+mode,()=>{const f=bots();if(mode==='duel')f.a.mode='duel';if(mode==='projectile')f.a.projectiles=[{x:705,z:0}];if(mode==='enemy')f.a.players.push({id:'fight',team:3,hp:100,x:710,z:0});if(mode==='airborne')f.p.grounded=false;if(mode==='bus')f.p.inBus=true;if(mode==='remembered')f.p.brain.memory=2;if(mode==='vehicle')f.p.vehicle='tank';run(f,7);assert.ok(f.calls()>350);});
test('bot records are discarded when their owner leaves',()=>{const f=bots();run(f,1);f.a.players=[];f.b.update(f.a,.1);assert.equal(f.b.records.size,0);});
test('bus pose is outside and above the vehicle and follows mouse orbit',()=>{const bus={x:10,y:50,z:20,ax:0,az:0,bx:0,bz:100};const a=busCameraPose(bus,{angle:0,pitch:0}),b=busCameraPose(bus,{angle:Math.PI/2,pitch:.2});assert.ok(Math.hypot(a.position.x-bus.x,a.position.z-bus.z)>15);assert.ok(a.position.y>=bus.y+1);assert.notEqual(a.position.x,b.position.x);assert.equal(a.fov,72);});
test('bus camera resets walking shake but does not modify player input or preferred mode',()=>{const pos={set(x,y,z){Object.assign(this,{x,y,z});}},cam={position:pos,fov:50,lookAt(){},updateProjectionMatrix(){},updateMatrixWorld(){}};const v={camera:cam,thirdPerson:false,shake:3},look={angle:.4,pitch:.1};applyBusCamera(v,{x:0,y:44,z:0},look,1/60);assert.equal(v.thirdPerson,false);assert.deepEqual(look,{angle:.4,pitch:.1});assert.equal(v.shake,0);assert.equal(cam.fov,72);});

test('boss retains five seconds of activity and finishes an attack outside the view',()=>{const a={map:{tiled:true},players:[],botBudget037:{clock:0}},b={hp:100,x:0,z:0};assert.equal(bossShouldThink(a,b),true);a.botBudget037.clock=5.01;assert.equal(bossShouldThink(a,b),false);b.act={id:'meteor'};assert.equal(bossShouldThink(a,b),true);a.botBudget037.clock=10;assert.equal(bossShouldThink(a,b),true);b.act=null;b.frozen=1;a.botBudget037.clock=20;assert.equal(bossShouldThink(a,b),true);b.frozen=0;a.botBudget037.clock=25.1;assert.equal(bossShouldThink(a,b),false);});
