import test from 'node:test';import assert from 'node:assert/strict';
import {armourFace,absorbArmour,armourSnapshot,refillArmour,armourProfile,damageContext} from '../src/tank-armour.js';
import {freshVehicle,consumeShot} from '../src/vehicle-specs.js';
import {ROCKETS,rocketSpec,wantsVehicleRocket,tickRocketRack,fireVehicleRocket,refillRocketRack,MAX_VEHICLE_PROJECTILES} from '../src/vehicle-rockets.js';
import {unlimitedDebugRockets} from '../src/developer-mode.js';
const tank=()=>freshVehicle({id:'t',kind:'tank',x:0,y:0,z:0});
const src={front:{x:0,y:1.3,z:20},rear:{x:0,y:1.3,z:-20},left:{x:-20,y:1.3,z:0},right:{x:20,y:1.3,z:0},top:{x:0,y:40,z:0}};
for(const face of Object.keys(src))test('independent armour plate: '+face,()=>{const v=tank(),before=armourSnapshot(v);const d=absorbArmour(v,100,{source:src[face]});assert.equal(d.face,face);assert.equal(d.hull,25);assert.equal(d.absorbed,75);for(const k of Object.keys(src))assert.equal(v.armour[k],before[k]-(k===face?75:0));});
test('armour direction follows chassis yaw rather than rotating turret',()=>{const v=tank();v.angle=Math.PI/2;v.turret=-2;assert.equal(armourFace(v,{x:20,y:1.3,z:0}),'front');assert.equal(armourFace(v,{x:0,y:1.3,z:-20}),'right');});
test('destroyed plate leaks all subsequent damage, without borrowing from adjacent sides',()=>{const v=tank();const d=absorbArmour(v,2000,{source:src.front});assert.equal(d.absorbed,420);assert.equal(d.hull,1580);assert.ok(d.broken);assert.equal(absorbArmour(v,100,{source:src.front}).hull,100);assert.equal(v.armour.rear,160);});
test('explosion position, not owner position, selects a plate and leaks more damage',()=>{const v=tank(),context=damageContext({_vehicleImpact037:{source:src.rear,kind:'blast'}},{x:0,y:0,z:100});const d=absorbArmour(v,100,context);assert.equal(d.face,'rear');assert.ok(Math.abs(d.hull-45)<1e-9);});
for(const kind of ['collision','environment'])test('plate cannot make ramming or a crash free: '+kind,()=>{const v=tank(),before=armourSnapshot(v);assert.equal(absorbArmour(v,100,{kind,source:src.front}).hull,100);assert.deepEqual(v.armour,before);});
test('service restores independent copies of plates',()=>{const a=tank(),b=tank();absorbArmour(a,100,{source:src.front});refillArmour(a);assert.deepEqual(a.armour,b.armour);a.armour.front=0;assert.equal(b.armour.front,420);});
test('snapshot plate arrays cannot modify the authoritative state',()=>{const v=tank(),s=armourSnapshot(v);s.front=0;assert.equal(v.armour.front,420);});
test('civilian and aircraft hulls do not acquire armour accidentally',()=>{for(const kind of ['car','plane']){const v=freshVehicle({id:kind,kind});assert.equal(v.armour,null);assert.equal(absorbArmour(v,100,{source:src.front}).hull,100);}});
test('non-finite and negative damage cannot heal or poison plates',()=>{const v=tank(),before=armourSnapshot(v);for(const n of [-1,Infinity,NaN])assert.equal(absorbArmour(v,n).hull,0);assert.deepEqual(v.armour,before);});
test('unknown variants cannot use prototype properties as an armour profile',()=>{const v=tank();for(const n of ['constructor','__proto__','toString']){v.variant=n;assert.equal(armourProfile(v).front,420);}});
function salvo(){const v=freshVehicle({id:'hydra',kind:'tank',variant:'twin',x:0,y:0,z:0}),p={id:'p',hp:100,vehicle:'hydra'};v.driver='p';return {v,p,s:{a:{players:[p],events:[],mode:'royale'},rounds:[],nextShot:0,ray:(_,__,r)=>({distance:r})}};}
function step(f,pressed,n=1){for(let i=0;i<n;i++){tickRocketRack(f.v,1/60);if(wantsVehicleRocket(f.v,pressed,unlimitedDebugRockets(f.s.a,f.p)))fireVehicleRocket(f.s,f.v,f.p);f.s.rounds=[];}}
test('one Q press completes six missiles, then waits without spontaneously firing another magazine',()=>{const f=salvo();step(f,true);step(f,false,300);assert.equal(f.v.rocketShot,6);assert.equal(f.v.rocketAmmo,6);assert.equal(f.v.rocketReserve,18);});
test('holding Q expends exactly thirty rockets across five magazines, no refill after exhaustion',()=>{const f=salvo();step(f,true,1800);assert.equal(f.v.rocketShot,30);assert.equal(f.v.rocketAmmo,0);assert.equal(f.v.rocketReserve,0);assert.equal(f.v.rocketBurstLeft,0);});
test('burst interval and magazine reload are respected at 60Hz',()=>{const f=salvo(),ticks=[];for(let t=0;t<800;t++){const n=f.v.rocketShot;step(f,true);if(n!==f.v.rocketShot)ticks.push(t);}assert.ok(ticks.length>=12);for(let i=1;i<6;i++)assert.ok(ticks[i]-ticks[i-1]>=5);assert.ok((ticks[6]-ticks[5])/60>=3.2);});
test('leaving the vehicle cancels pending shots and cannot shoot with no driver',()=>{const f=salvo();step(f,true);f.v.driver=null;step(f,false,60);assert.equal(f.v.rocketShot,1);assert.equal(f.v.rocketBurstLeft,0);});
test('projectile budget stalls the burst without deleting existing missiles or spending ammo',()=>{const f=salvo();f.s.rounds=Array.from({length:MAX_VEHICLE_PROJECTILES},(_,i)=>({id:i}));wantsVehicleRocket(f.v,true);assert.equal(fireVehicleRocket(f.s,f.v,f.p),false);assert.equal(f.v.rocketAmmo,6);assert.equal(f.v.rocketBurstLeft,6);assert.equal(f.s.rounds.length,64);});
test('frozen driver cannot release rockets from a pending burst',()=>{const f=salvo();wantsVehicleRocket(f.v,true);f.p.frozen=1;assert.equal(fireVehicleRocket(f.s,f.v,f.p),false);assert.equal(f.v.rocketAmmo,6);});
test('service replenishes thirty finite missiles, not infinity',()=>{const f=salvo();step(f,true,1800);refillRocketRack(f.v);assert.equal(f.v.rocketAmmo+f.v.rocketReserve,30);assert.equal(f.v.rocketShot,30);});
test('explicit solo Debug infinite option still exists, but never public Royale',()=>{const f=salvo();f.p.cheats={infinite:true};f.s.a.allowCheats=true;f.s.a.mode='royale';step(f,true,1800);assert.equal(f.v.rocketShot,30);f.s.a.mode='debug';step(f,true,1);assert.equal(f.v.rocketAmmo,6,'explicit Debug infinite option restarts an empty launcher');refillRocketRack(f.v);step(f,true,300);assert.ok(f.v.rocketShot>30);assert.equal(f.v.rocketAmmo,6);});
test('aircraft rockets use new blast damage and radius without changing their finite eight-round load',()=>{const v=freshVehicle({id:'p',kind:'plane'});assert.equal(ROCKETS.plane.damage,260);assert.equal(rocketSpec(v).radius,6);assert.equal(v.rocketAmmo,8);assert.equal(v.rocketReserve,0);});
test('HYDRA normal gun ammunition is finite as well as its missile magazine',()=>{const f=salvo(),before=f.v.ammo;assert.ok(consumeShot(f.v));assert.equal(f.v.ammo,before-1);});
