import test from 'node:test';import assert from 'node:assert/strict';
import {unlimitedDebugRockets,developerMode,setDeveloperMode} from '../src/developer-mode.js';
import {ROCKETS,fireVehicleRocket,tickRocketRack} from '../src/vehicle-rockets.js';
import {freshVehicle} from '../src/vehicle-specs.js';
import {ramContacts,ramAhead} from '../src/vehicle-ram.js';
import {furnitureFittings} from '../src/interior-fittings.js';
test('developer mode is opt-in and uses no server permission or hidden credentials',()=>{assert.equal(developerMode(),false);assert.equal(setDeveloperMode(true),true);assert.equal(developerMode(),true);assert.equal(setDeveloperMode(false),false);});
for(const mode of ['royale','duel','classic','survival','debug'])test('unlimited rockets policy / '+mode,()=>{const a={mode,allowCheats:true},p={hp:100,cheats:{infinite:true},bot:false};assert.equal(unlimitedDebugRockets(a,p),mode==='debug');for(const flag of [false,undefined])assert.equal(unlimitedDebugRockets({...a,allowCheats:flag},p),false);assert.equal(unlimitedDebugRockets(a,{...p,bot:true}),false);});
for(const kind of ['tank','plane'])test(kind+': infinite Debug ammo still obeys launcher cadence and human ownership',()=>{const v=freshVehicle({id:'v',kind,x:0,y:10,z:0}),p={id:'p',hp:100,team:1,vehicle:'v',cheats:{infinite:true}};v.driver='p';v.rocketAmmo=0;v.rocketReserve=0;
 const a={mode:'debug',allowCheats:true,players:[p],map:{limit:{x:1000,z:1000}},events:[]},system={a,rounds:[],nextShot:0,get:()=>v,ray:(o,d,r)=>({distance:r})};
 for(let i=0;i<20;i++){tickRocketRack(v,1);assert.ok(fireVehicleRocket(system,v,p));assert.equal(v.rocketAmmo,ROCKETS[kind].magazine);assert.equal(fireVehicleRocket(system,v,p),false);system.rounds.length=0;}
});
test('changing the UI flag alone cannot grant a hosted player infinite rocket ammunition',()=>{setDeveloperMode(true);const p={hp:100,cheats:{infinite:true}};assert.equal(unlimitedDebugRockets({mode:'royale',allowCheats:false},p),false);setDeveloperMode(false);});
function ramScene(){const v=freshVehicle({id:'plane',kind:'plane',x:0,y:4,z:0}),p={id:'pilot',hp:100,team:1,vehicle:'plane'};v.speed=32;v.airborne=true;v.driver=p.id;const wall={x:0,y:5,z:6,w:8,h:4,d:.3,hp:200,part:'wall',panel:0};const a={players:[p],map:{obstacles:[wall]},colliders:new Map([[wall,{}]]),events:[],destruction:{roofs:[]},damageObstacle(o,n){o.hp-=n;if(o.hp<=0){this.colliders.delete(o);this.map.obstacles.splice(this.map.obstacles.indexOf(o),1);}},removeObs(){}};
 const system={a,clock:0,get:()=>null,damage(id,n){if(id===v.id)v.hp-=n;}};return {v,a,wall,system};}
test('airborne aircraft rams forward obstacles through normal damage and also takes crash damage',()=>{const {v,a,wall,system}=ramScene(),hp=v.hp;assert.ok(ramAhead(system,v,{x:0,y:0,z:4,oldAngle:0}));assert.ok(wall.hp<=0);assert.equal(a.colliders.has(wall),false);assert.ok(v.hp<hp);assert.ok(a.events.some(e=>e.type==='vehicle-ram'));});
test('aircraft can ram while descending, not only horizontally; taxi contact is not a demolition tool',()=>{const {v,a}=ramScene();a.map.obstacles=[{x:0,y:1,z:0,w:10,h:.25,d:10,hp:200,part:'roof'}];assert.ok(ramContacts(a.map,v,{x:0,y:-4,z:0,oldAngle:0}).length);v.airborne=false;v.speed=4;assert.equal(ramContacts(a.map,v,{x:0,y:0,z:1,oldAngle:0}).length,0);});
test('furniture embellishments are finite, yaw-relative and keep their native destruction owner',()=>{for(const model of ['desk','sink','kitchen-cabinet','side-table'])for(const rot of [0,Math.PI/2,Math.PI]){const d={model,id:23,building:4,storey:2,x:123,y:7.44,z:-90,rot},f=furnitureFittings(d);assert.ok(f.length>0);for(const p of f){assert.equal(p.decor,23);assert.equal(p.building,4);assert.ok([p.x,p.y,p.z,p.w,p.h,p.d,p.rot].every(Number.isFinite));assert.ok(Math.abs(p.x-d.x)<1&&Math.abs(p.z-d.z)<1);}}});
