import test from 'node:test';import assert from 'node:assert/strict';
import {PortalBridge} from '../src/sdk.js';
import {RewardController,cleanReceipts,REWARD_COOLDOWN_MS} from '../src/portal-rewards.js';
function fixture(options={}){
 const events=[],save=new Map();let callbacks,listener,auth=0;
 const sdk={environment:options.environment||'crazygames',init:async()=>{},game:{gameplayStart(){events.push('start');},gameplayStop(){events.push('stop');}},data:{getItem:k=>save.get(k)||null,setItem:(k,v)=>save.set(k,v)},
  user:{isUserAccountAvailable:options.accountAvailable!==false,getUser:async()=>options.user||null,showAuthPrompt:async()=>{auth++;return {username:'Portal.User'};},addAuthListener(l){listener=l;}},
  ad:{requestAd(type,c){assert.equal(type,'rewarded');callbacks=c;if(options.throwAd)throw Error('request failed');}}};
 const bridge=new PortalBridge({sdk,fullAds:options.full!==false,allowDemo:options.allowDemo});
 bridge.setHooks({block:b=>events.push('block:'+b),mute:b=>events.push('mute:'+b)});
 return {bridge,sdk,events,save,get callbacks(){return callbacks;},get auth(){return auth;},change:u=>listener(u)};
}
test('initialization reads user but never opens sign-in',async()=>{const f=fixture();await f.bridge.initialize();assert.equal(f.auth,0);assert.equal(f.bridge.user,null);});
test('v3 availability is a property, not a function',async()=>{const f=fixture({accountAvailable:false});f.sdk.user.getUser=f.sdk.user.addAuthListener=()=>{throw Error('should not be called');};await f.bridge.initialize();assert.equal(f.bridge.accountsAvailable,false);});
test('authenticated portal user is available automatically',async()=>{const f=fixture({user:{username:'Account.123'}});await f.bridge.initialize();assert.equal(f.bridge.user.username,'Account.123');});
test('guest explicitly opens CrazyGames prompt',async()=>{const f=fixture();await f.bridge.initialize();await f.bridge.login();assert.equal(f.auth,1);});
test('disabled environment has no accounts, ads or data',async()=>{const f=fixture({environment:'disabled'});await f.bridge.initialize();assert.equal(f.bridge.active,false);assert.equal(f.bridge.storage,null);assert.equal((await f.bridge.requestRewarded()).finished,false);});
test('basic build never calls advertising',async()=>{const f=fixture({full:false});await f.bridge.initialize();assert.equal((await f.bridge.requestRewarded()).reason,'unavailable');assert.equal(f.callbacks,undefined);});
test('Data used for guests as well as signed-in users',async()=>{const f=fixture();await f.bridge.initialize();assert.equal(f.bridge.storage,f.sdk.data);});
test('gameplay notifications are idempotent',async()=>{const f=fixture();await f.bridge.initialize();f.bridge.gameplay(true);f.bridge.gameplay(true);f.bridge.gameplay(false);f.bridge.gameplay(false);assert.deepEqual(f.events,['start','stop']);});
test('request blocks UI, mute occurs only after adStarted',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();assert.deepEqual(f.events,['block:true']);f.callbacks.adStarted();f.callbacks.adFinished();await p;assert.deepEqual(f.events,['block:true','mute:true','mute:false','block:false']);});
test('adError before start does not flicker audio',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();f.callbacks.adError({code:'unfilled'});assert.equal((await p).finished,false);assert.deepEqual(f.events,['block:true','block:false']);});
test('failure while playing ad restores sound once',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();f.callbacks.adStarted();f.callbacks.adStarted();f.callbacks.adError({code:'failed'});f.callbacks.adFinished();await p;assert.equal(f.events.filter(x=>x==='mute:false').length,1);});
test('repeated finish cannot grant a second result',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();f.callbacks.adFinished();f.callbacks.adFinished();assert.equal((await p).finished,true);assert.equal(f.events.filter(x=>x==='block:false').length,1);});
test('throwing ad request restores play state',async()=>{const f=fixture({throwAd:true});await f.bridge.initialize();f.bridge.gameplay(true);assert.equal((await f.bridge.requestRewarded()).finished,false);assert.equal(f.bridge.busy,false);assert.equal(f.events.at(-1),'start');});
test('simultaneous ad requests are rejected',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();assert.equal((await f.bridge.requestRewarded()).reason,'busy');f.callbacks.adError({});await p;});
test('account changes during ad invalidate the reward',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();f.change({username:'Other'});f.callbacks.adFinished();assert.equal((await p).reason,'account-changed');});
test('local SDK demo never grants real rewards',async()=>{const f=fixture({environment:'local',allowDemo:true});await f.bridge.initialize();const p=f.bridge.requestRewarded();f.callbacks.adFinished();assert.deepEqual(await p,{finished:false,reason:'demo'});});
test('sign in unavailable during ad',async()=>{const f=fixture();await f.bridge.initialize();const p=f.bridge.requestRewarded();await assert.rejects(f.bridge.login());f.callbacks.adError({});await p;});
function economy({matches=1}={}){let profile={coins:350,owned:['soldier'],matches},writes=0,fail=false,t=1e9;const f=fixture();const controller=new RewardController({portal:f.bridge,getProfile:()=>profile,writeProfile:p=>{if(fail)throw Error('Data unavailable');profile=p;writes++;},now:()=>t,makeId:()=> 'receipt-123456789'});return {f,controller,get profile(){return profile;},get writes(){return writes;},setFail:b=>fail=b,time:n=>t=n};}
test('no rewards before the first completed match',async()=>{const e=economy({matches:0});await e.f.bridge.initialize();assert.equal((await e.controller.request('credits',true)).reason,'not-ready');assert.equal(e.f.callbacks,undefined);});
test('rewarded ads are rejected during a live match',async()=>{const e=economy();await e.f.bridge.initialize();assert.equal((await e.controller.request('credits',false)).ok,false);});
test('coins granted and persisted only after adFinished',async()=>{const e=economy();await e.f.bridge.initialize();const p=e.controller.request('credits',true);assert.equal(e.profile.coins,350);e.f.callbacks.adStarted();assert.equal(e.writes,0);e.f.callbacks.adFinished();assert.equal((await p).ok,true);assert.equal(e.profile.coins,450);assert.equal(e.writes,1);});
test('ad error leaves wallet unchanged',async()=>{const e=economy();await e.f.bridge.initialize();const p=e.controller.request('credits',true);e.f.callbacks.adError({});await p;assert.equal(e.profile.coins,350);assert.equal(e.writes,0);});
test('skin becomes permanently owned after one ad',async()=>{const e=economy();await e.f.bridge.initialize();const p=e.controller.request('hazmat',true);e.f.callbacks.adFinished();await p;assert.ok(e.profile.owned.includes('hazmat'));});
test('emote becomes owned after one ad',async()=>{const e=economy();await e.f.bridge.initialize();const p=e.controller.request('crouchdance',true);e.f.callbacks.adFinished();await p;assert.ok(e.profile.owned.includes('crouchdance'));});
test('save failure retains reward for retry without another ad',async()=>{const e=economy();await e.f.bridge.initialize();e.setFail(true);const p=e.controller.request('credits',true);e.f.callbacks.adFinished();assert.equal((await p).retry,true);assert.equal(e.profile.coins,350);e.setFail(false);assert.equal(e.controller.commit().ok,true);assert.equal(e.profile.coins,450);assert.equal(e.controller.commit().ok,false);});
test('cannot chain ads during cooldown',async()=>{const e=economy();await e.f.bridge.initialize();const p=e.controller.request('credits',true);e.f.callbacks.adFinished();await p;assert.equal(e.controller.remaining(),REWARD_COOLDOWN_MS);assert.equal((await e.controller.request('hazmat',true)).ok,false);});
test('retry cannot apply to another account',async()=>{const e=economy();await e.f.bridge.initialize();e.setFail(true);const p=e.controller.request('credits',true);e.f.callbacks.adFinished();await p;e.f.change({username:'Other'});e.setFail(false);assert.equal(e.controller.commit().reason,'account-changed');assert.equal(e.profile.coins,350);});
test('unknown reward cannot change profile',async()=>{const e=economy();await e.f.bridge.initialize();assert.equal((await e.controller.request('__proto__',true)).ok,false);});
test('receipt log is bounded and removes malformed entries',()=>{const l=cleanReceipts({at:NaN,ids:[...Array(100).fill('valid-123456'),{},'x']});assert.equal(l.at,0);assert.equal(l.ids.length,32);});

 test('receipt ID works in browsers without crypto.randomUUID',async()=>{const {newRewardId}=await import('../src/portal-rewards.js');const cryptoImpl={getRandomValues:globalThis.crypto.getRandomValues.bind(globalThis.crypto)};const a=newRewardId(cryptoImpl),b=newRewardId(cryptoImpl);assert.match(a,/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);assert.notEqual(a,b);});
