import test from 'node:test';import assert from 'node:assert/strict';import R from '@dimforge/rapier3d-compat';
import {ColliderBudget} from '../src/collider-budget.js';import {regionMesh} from '../src/terrain-region.js';
import {freshVehicle,vehicleDimensions} from '../src/vehicle-specs.js';
import {absorbArmour} from '../src/tank-armour.js';
await R.init();
function arena(){const map={tiled:true,limit:{x:512,z:512},obstacles:[]};map.obstacles.grid={query(x0,z0,x1,z1,fn){for(const o of map.obstacles)if(o.x+o.w/2>=x0&&o.x-o.w/2<=x1&&o.z+o.d/2>=z0&&o.z-o.d/2<=z1)fn(o);}};const a={map,world:new R.World({x:0,y:0,z:0}),players:[{id:'a',hp:100,x:0,y:0,z:0}],colliders:new Map()};const b=new ColliderBudget(a,R,(map,rect)=>regionMesh(map,()=>0,2,rect));a.addCollider=o=>{if(b.defer(o))return;a.colliders.set(o,a.world.createCollider(R.ColliderDesc.cuboid(o.w/2,o.h/2,o.d/2).setTranslation(o.x,o.y,o.z)));};return {a,b};}
test('native Rapier: a recent offscreen wall persists for five seconds, then reappears when needed',()=>{const {a,b}=arena();try{const o={x:5,y:1.5,z:5,w:4,h:3,d:.3};a.map.obstacles.push(o);a.addCollider(o);b.update(.2);a.world.step();let c=a.colliders.get(o);assert.ok(c?.isValid());a.players[0].x=400;a.players[0].z=400;b.update(.2);b.update(4.7);assert.ok(c.isValid());b.update(.2);assert.equal(c.isValid(),false);assert.deepEqual(a.colliders.get(o),[]);a.players[0].x=0;a.players[0].z=0;b.update(.2);assert.ok(a.colliders.get(o).isValid());}finally{a.world.free();}});
test('native Rapier: other live players keep their sector solid independent of local view',()=>{const {a,b}=arena();try{const o={x:400,y:1,z:400,w:5,h:2,d:1};a.map.obstacles.push(o);a.addCollider(o);a.players.push({id:'b',hp:100,x:400,y:0,z:399});b.update(6);assert.ok(a.colliders.get(o).isValid());a.world.step();assert.ok(a.world.castRay(new R.Ray({x:400,y:1,z:395},{x:0,y:0,z:1}),10,true));}finally{a.world.free();}});
for(const [face,origin,dir] of [['front',{x:0,y:1.3,z:20},{x:0,y:0,z:-1}],['rear',{x:0,y:1.3,z:-20},{x:0,y:0,z:1}],['top',{x:0,y:20,z:0},{x:0,y:-1,z:0}]])test('native Rapier hull hit drains the matching armour plate: '+face,()=>{const world=new R.World({x:0,y:0,z:0});try{const v=freshVehicle({id:'t',kind:'tank',x:0,y:0,z:0}),s=vehicleDimensions(v);world.createCollider(R.ColliderDesc.cuboid(s.w/2,s.h/2,s.d/2).setTranslation(0,s.h/2,0));world.step();const hit=world.castRay(new R.Ray(origin,dir),40,true);assert.ok(hit);const result=absorbArmour(v,100,{source:origin});assert.equal(result.face,face);assert.equal(result.hull,25);}finally{world.free();}});
