import test from 'node:test';
import assert from 'node:assert/strict';
import {sweepVehicleContacts} from '../src/vehicle-contact.js';
import {VehicleMotionTrack,VehiclePresentationClock} from '../src/vehicle-motion.js';
import {VehicleCameraState} from '../src/vehicle-camera.js';
import {StreamFrameBudget} from '../src/stream-budget.js';
import {updateVehicleObstacle} from '../src/vehicle-spatial.js';
import {SectorIndex,SECTOR_SIZE} from '../src/world-sectors.js';
import {leafBounds} from '../src/architecture-geometry.js';
const near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
function car(yaw=0,extra={}){const p={x:0,y:1.07,z:0,yaw,w:2,h:2,t:4};return {...leafBounds(p),vehicleId:'car',doorLeaf:p,hp:420,...extra};}
const level=o=>({obstacles:[o]});
for(const yaw of [0,Math.PI/4,Math.PI/2,Math.PI])for(const side of [-1,1])test(`swept contact stops crossing at yaw ${yaw}, side ${side}`,()=>{
 const f={x:Math.sin(yaw),z:Math.cos(yaw)},p={x:f.x*side*5,y:.1,z:f.z*side*5};
 const m=sweepVehicleContacts(level(car(yaw)),p,{x:-f.x*side*12,y:0,z:-f.z*side*12});assert.ok(m.contacts>0);assert.ok(Math.hypot(m.x,m.z)<3);assert.ok((p.x+m.x)*f.x*side+(p.z+m.z)*f.z*side>2.34);
});
test('long frame cannot tunnel through a car',()=>{assert.ok(sweepVehicleContacts(level(car()),{x:0,y:0,z:-10},{x:0,y:0,z:30}).z<7.7);});
test('wrecked but uncrushed vehicles remain solid',()=>{assert.ok(sweepVehicleContacts(level(car(0,{hp:0})),{x:0,y:0,z:-4},{x:0,y:0,z:8}).contacts>0);});
test('crushed and removed vehicle no longer blocks',()=>{near(sweepVehicleContacts({obstacles:[]},{x:0,y:0,z:-4},{x:0,y:0,z:8}).z,8);});
test('mounted player ignores their own hull',()=>{near(sweepVehicleContacts(level(car()),{x:0,y:1,z:0,vehicle:'car'},{x:0,y:0,z:8}).z,8);});
test('falling character can land on a car roof',()=>{const m=sweepVehicleContacts(level(car()),{x:0,y:6,z:0},{x:0,y:-8,z:0});assert.ok(m.supported);near(6+m.y,2.12,.002);});
test('jumping above a car remains possible',()=>{near(sweepVehicleContacts(level(car()),{x:0,y:3,z:-4},{x:0,y:0,z:8}).z,8);});
test('sliding along the side stays free',()=>{near(sweepVehicleContacts(level(car()),{x:1.37,y:0,z:0},{x:0,y:0,z:2}).z,2);});
test('partly overlapping character may retreat but not continue through',()=>{const p={x:0,y:0,z:-2.3};near(sweepVehicleContacts(level(car()),p,{x:0,y:0,z:-1}).z,-1);near(sweepVehicleContacts(level(car()),p,{x:0,y:0,z:1}).z,0);});
test('diagonal movement preserves the unblocked component',()=>{const m=sweepVehicleContacts(level(car()),{x:0,y:0,z:-4},{x:3,y:0,z:5});assert.ok(m.x>2.5&&m.z<2);});
test('a car on another floor does not block',()=>{const o=car();o.y+=10;o.doorLeaf.y+=10;near(sweepVehicleContacts(level(o),{x:0,y:0,z:-4},{x:0,y:0,z:8}).z,8);});
test('contact query is restricted to the swept footprint',()=>{let q;const map={obstacles:[]};map.obstacles.grid={query(...a){q=a.slice(0,4);a[4](car());}};assert.ok(sweepVehicleContacts(map,{x:0,y:0,z:-4},{x:0,y:0,z:8}).contacts>0);assert.ok(q[2]-q[0]<1);});
for(const hz of [30,60,120,144])test(`20 Hz samples interpolate linearly at ${hz} Hz`,()=>{const t=new VehicleMotionTrack();for(let i=0;i<12;i++)t.push({x:i*1.2},i*.05);for(let frame=0;frame<=hz*.5;frame++)near(t.at(frame/hz).x,24*frame/hz);});
test('packet loss never extrapolates through a wall',()=>{const t=new VehicleMotionTrack();t.push({x:0},0);t.push({x:1},.1);near(t.at(.5).x,1);});
test('angles interpolate across the short wrap direction',()=>{const t=new VehicleMotionTrack();t.push({angle:3.1,turret:3.1},0);t.push({angle:-3.1,turret:-3.1},.1);near(t.at(.05).angle,Math.PI);near(t.at(.05).turret,Math.PI);});
test('teleports reset pose history',()=>{const t=new VehicleMotionTrack();t.push({x:0},0);t.push({x:100},.1);assert.ok(t.discontinuity);near(t.at(0).x,100);});
test('new match resets the presentation clock',()=>{const c=new VehiclePresentationClock();c.update({tick:600},1/60);const n=c.generation;c.update({tick:1},1/60);assert.equal(c.generation,n+1);});
test('paused display samples the current frozen pose',()=>{near(new VehiclePresentationClock().update({tick:90},0).time,1.5);});
test('one build per frame, with fair scheduling',()=>{const b=new StreamFrameBudget(()=>0),jobs=[];for(let i=0;i<12;i++){b.begin();b.pending={world:50,ground:50,scenery:50};let n=0;for(const k of ['world','ground','scenery'])b.run(k,()=>{n++;jobs.push(k);});assert.equal(n,1);}assert.equal(jobs.filter(k=>k==='scenery').length,4);assert.equal(jobs.filter(k=>k==='ground').length,4);});
test('empty queues do not waste a free build slot',()=>{const b=new StreamFrameBudget(()=>0);b.pending.scenery=1;assert.ok(b.run('scenery',()=>{}));});
test('moving inside a bucket does not repeatedly rebuild the grid',()=>{let edits=0;const g={range:o=>[Math.floor((o.x-o.w/2)/8),Math.floor((o.x+o.w/2)/8),Math.floor((o.z-o.d/2)/8),Math.floor((o.z+o.d/2)/8)],remove(){edits++;},add(){edits++;}};const obstacles=[];obstacles.grid=g;obstacles.lowGrid=g;const p={x:4,y:1,z:4,w:1,h:2,d:1,doorLeaf:{yaw:0}};for(let i=0;i<120;i++)updateVehicleObstacle({obstacles},p,{...p,x:4+i*.001,doorLeaf:{yaw:0}});assert.equal(edits,0);updateVehicleObstacle({obstacles},p,{...p,x:12});assert.equal(edits,4);});
test('same-count replacement invalidates the sector cache',()=>{const o={x:0,y:1,z:0,w:2,h:2,d:2,part:'car',decor:0},m={buildings:[],obstacles:[o],decor:[],doors:[],windows:[],trees:[],roads:[],paths:[]};const idx=new SectorIndex(m),s=idx.get(0,0);assert.ok(idx.subset(s).obstacles.includes(o));m.obstacles[0]={x:30,z:0,w:2,d:2};m.obstacleVersion=1;assert.ok(!idx.subset(s).obstacles.includes(o));});
test('a build sector has one quarter the previous area, without resizing the map',()=>{assert.equal(SECTOR_SIZE**2,192**2/4);});
test('short alternating wall gaps do not pump the camera outward',()=>{const c=new VehicleCameraState(),v={id:'car',kind:'car',angle:0,pitch:0},p={x:0,y:1.5,z:0},hit=(o,d,r)=>r<=1?r:Math.min(2,r),free=(o,d,r)=>r;c.step(v,p,{},0,hit,()=>0);for(let i=0;i<120;i++)near(c.step(v,p,{},1/60,i%2?hit:free,()=>0).distance,1.7);for(let i=0;i<120;i++)c.step(v,p,{},1/60,free,()=>0);assert.ok(c.distance>6);});
