// Sources and adaptation details are in public/ASSET-CREDITS.md.
import { BUILDING_FIT } from './building-fit.js';
export const BUILDING_TYPES = [
  ['cottage', 'Cottage', 'suburban-a', 11, 11, 8, 0xe3c993, 0x777950, 'home'],
  ['villa', 'Villa', 'suburban-b', 14, 12, 7.5, 0xe0d4ad, 0x966b59, 'home'],
  ['duplex', 'Duplex', 'suburban-c', 13, 12, 11, 0xccbca0, 0x826d66, 'home'],
  ['bungalow', 'Bungalow', 'suburban-d', 12, 10, 7.5, 0xd9c4a0, 0x697e61, 'home'],
  ['townhouse', 'Townhouse', 'suburban-e', 12, 12, 12, 0xc2b595, 0x5e7180, 'home'],
  ['lodge', 'Porch House', 'suburban-f', 13, 11, 9.5, 0xe8c8a6, 0x9f6754, 'home'],
  ['residence', 'Residence', 'suburban-g', 15, 13, 8, 0xc3d0c1, 0x63776f, 'home'],
  ['cafe', 'Cafe', 'commercial-a', 11, 11, 15.5, 0xd1ab85, 0xb76d48, 'shop'],
  ['pharmacy', 'Pharmacy', 'commercial-b', 11, 12, 15.5, 0xc6dad0, 0x3f8c7a, 'shop'],
  ['bookshop', 'Bookshop', 'commercial-c', 12, 10, 10, 0xdfbda1, 0x786b79, 'shop'],
  ['market', 'Market', 'commercial-d', 15, 13, 21, 0xd9c99b, 0x5e8574, 'shop'],
  ['hotel', 'Hotel', 'commercial-e', 13, 13, 6.5, 0xd2b7a3, 0x817d8c, 'office'],
  ['office', 'Office', 'commercial-f', 13, 12, 22.5, 0xa4bfc2, 0x566e83, 'office'],
  ['clinic', 'Clinic', 'commercial-g', 14, 12, 23, 0xc4d3c4, 0x65988c, 'office'],
  ['bank', 'Bank', 'commercial-h', 14, 13, 18.5, 0xd1c9b6, 0x737b81, 'office'],
  ['warehouse', 'Warehouse', 'industrial-a', 15, 14, 9.5, 0xb3b8ad, 0x5f7275, 'industry'],
  ['factory', 'Factory', 'industrial-b', 15, 14, 9.5, 0xc79d80, 0x6b6c6a, 'industry'],
  ['workshop', 'Workshop', 'industrial-c', 13, 13, 8, 0xa7c3bc, 0x536d67, 'industry'],
  ['hangar', 'Hangar', 'industrial-d', 16, 14, 13.5, 0xc2c8bd, 0x666f7a, 'industry'],
  ['powerstation', 'Power Station', 'industrial-e', 15, 14, 16, 0xd3c29a, 0x947d50, 'industry'],
  ['mall', 'Shopping Centre', 'commercial-i', 36, 16, 23, 0xd7c4a6, 0x5c9292, 'shop', [2, 1]],
  ['hospital', 'Hospital', 'commercial-j', 16, 42, 19, 0xd5ded6, 0x499889, 'office', [1, 2]],
  ['university', 'University', 'commercial-k', 36, 16, 25, 0xdbb792, 0x8c6859, 'office', [2, 1]],
  ['terminal', 'Station', 'commercial-l', 36, 16, 28.5, 0xb8c6c2, 0x537582, 'office', [2, 1]],
  ['distribution', 'Logistics Centre', 'industrial-f', 16, 42, 24, 0xb6c0b7, 0x6d8382, 'industry', [1, 2]],
  ['refinery', 'Factory Complex', 'industrial-g', 36, 16, 15, 0xbab5a4, 0x9b7855, 'industry', [2, 1]],
  ['chalet', 'Chalet', 'suburban-h', 13, 13, 9, 0xc7ac87, 0x6b7d56, 'home'],
  ['guesthouse', 'Guesthouse', 'suburban-i', 14, 12, 8.5, 0xd5baa4, 0x9b7264, 'home'],
  ['courthouse', 'Mansard House', 'suburban-j', 13, 14, 9, 0xd5ceb8, 0x758b8a, 'home'],
  ['pavilion', 'City Pavilion', 'suburban-k', 14, 12, 15.5, 0xc4d2bb, 0x5e936d, 'shop'],
].map(([type, sign, model, w, d, height, color, accent, category, plots = [1, 1]]) => ({
  type,
  sign,
  model,
  w,
  d,
  // Storeys above the ground floor are built from wall panels; the model supplies only the roof on top.
  height: BUILDING_FIT[model]?.height ?? height,
  storeys: BUILDING_FIT[model]?.storeys ?? 0,
  color,
  accent,
  category,
  plots,
}));
// Weapon types. Indices are part of the network protocol and saved loadouts: append, never reorder.
// category: melee | primary | secondary | power. `starter` weapons may be chosen in the pre-match loadout.
// fp: first-person model length (m) and rotation; char: node name on the character rig or a mounted model.
const H = Math.PI / 2;
export const WEAPONS = [
  {
    name: 'RANGER',
    ru: 'Assault Rifle',
    model: 'rifle',
    category: 'primary',
    starter: true,
    mag: 24,
    reserve: 120,
    damage: 18,
    pellets: 1,
    spread: 0.035,
    interval: 0.13,
    reload: 1.5,
    range: 80,
    color: '#a5dac4',
    loot: 10,
    fp: { len: 0.66, rot: [0, -H, 0] },
    char: 'AK',
  },
  {
    name: 'BREAKER',
    ru: 'Shotgun',
    model: 'shotgun',
    category: 'primary',
    starter: true,
    mag: 6,
    reserve: 30,
    damage: 14,
    pellets: 8,
    spread: 0.21,
    interval: 0.78,
    reload: 1.9,
    range: 23,
    color: '#f4ab67',
    loot: 9,
    fp: { len: 0.78, rot: [0, -H, 0] },
    char: 'Shotgun',
  },
  {
    name: 'SIDEKICK',
    ru: 'Pistol',
    model: 'pistol',
    category: 'secondary',
    starter: true,
    mag: 12,
    reserve: 72,
    damage: 30,
    pellets: 1,
    spread: 0.012,
    interval: 0.32,
    reload: 1.1,
    range: 50,
    color: '#cfbbef',
    loot: 8,
    fp: { len: 0.34, rot: [0, -H, 0] },
    char: 'Pistol',
  },
  {
    name: 'SWIFT',
    ru: 'SMG',
    model: 'smg',
    category: 'primary',
    starter: true,
    mag: 32,
    reserve: 160,
    damage: 13,
    pellets: 1,
    spread: 0.055,
    interval: 0.075,
    reload: 1.4,
    range: 45,
    color: '#89c8de',
    loot: 9,
    fp: { len: 0.49, rot: [0, -H, 0] },
    char: 'SMG',
  },
  {
    name: 'TITAN',
    ru: 'Machine Gun',
    model: 'lmg',
    category: 'primary',
    mag: 70,
    reserve: 210,
    damage: 20,
    pellets: 1,
    spread: 0.065,
    interval: 0.105,
    reload: 3.2,
    range: 90,
    color: '#d5c785',
    loot: 5,
    fp: { len: 0.77, rot: [0, Math.PI, 0] },
    char: 'ShortCannon',
    iconRot: [0, H, 0],
  },
  {
    name: 'LONGSHOT',
    ru: 'Sniper Rifle',
    model: 'sniper',
    category: 'power',
    mag: 5,
    reserve: 25,
    damage: 85,
    pellets: 1,
    spread: 0.003,
    interval: 1.15,
    reload: 2.3,
    range: 180,
    zoom: 27,
    color: '#b7c7ec',
    loot: 4,
    fp: { len: 0.94, rot: [0, -H, 0] },
    char: 'Sniper',
  },
  {
    name: 'COMET',
    ru: 'Rocket Launcher',
    model: 'rocket',
    category: 'power',
    mag: 1,
    reserve: 6,
    damage: 110,
    pellets: 1,
    spread: 0,
    interval: 1.2,
    reload: 2.5,
    range: 130,
    speed: 32,
    radius: 6,
    projectile: 'rocket',
    color: '#ee9688',
    loot: 3,
    fp: { len: 0.85, rot: [0, -H, 0] },
    char: 'RocketLauncher',
  },
  // 0.7 additions
  {
    name: 'FANG',
    ru: 'Combat Knife',
    model: 'knife',
    category: 'melee',
    starter: true,
    melee: true,
    damage: 34,
    interval: 0.42,
    range: 2.3,
    arc: 0.75,
    move: 1.08,
    color: '#d9dde3',
    loot: 3,
    fp: { len: 0.36, rot: [-H, 0, 0] },
    char: 'Knife_1',
    iconRot: [0, 0, H],
  },
  {
    name: 'SPADE',
    ru: 'Shovel',
    model: 'shovel',
    category: 'melee',
    starter: true,
    melee: true,
    damage: 62,
    interval: 0.95,
    range: 2.8,
    arc: 0.9,
    move: 1.0,
    color: '#c8a27a',
    loot: 3,
    fp: { len: 0.64, rot: [H, H, 0], pivot: [0.55, 0.1, 0.3] },
    char: 'Shovel',
    iconRot: [0, 0, H],
  },
  {
    name: 'RONIN',
    ru: 'Katana',
    model: 'katana',
    category: 'melee',
    starter: true,
    melee: true,
    damage: 46,
    interval: 0.6,
    range: 3.1,
    arc: 1.1,
    move: 1.05,
    color: '#e8a0a8',
    loot: 2,
    fp: { len: 0.95, rot: [0, -H, 0], pivot: [0.45, 0.25, 0.6] },
    char: 'mount:katana',
    iconRot: [0, 0, 0.2],
  },
  {
    name: 'VIPER',
    ru: 'Revolver',
    model: 'revolver',
    category: 'secondary',
    starter: true,
    mag: 6,
    reserve: 36,
    damage: 42,
    pellets: 1,
    spread: 0.01,
    interval: 0.5,
    reload: 2.0,
    range: 60,
    color: '#e3c690',
    loot: 7,
    fp: { len: 0.36, rot: [0, H, 0] },
    char: 'Revolver',
    iconRot: [0, Math.PI, 0],
  },
  {
    name: 'HAMMER',
    ru: 'Hand Cannon',
    model: 'handcannon',
    category: 'secondary',
    mag: 5,
    reserve: 25,
    damage: 58,
    pellets: 1,
    spread: 0.018,
    interval: 0.75,
    reload: 2.2,
    range: 45,
    color: '#f0b07a',
    loot: 5,
    fp: { len: 0.34, rot: [0, H, 0] },
    char: 'Revolver_Small',
    iconRot: [0, Math.PI, 0],
  },
  {
    name: 'HAWK',
    ru: 'Marksman Rifle',
    model: 'marksman',
    category: 'primary',
    mag: 10,
    reserve: 50,
    damage: 44,
    pellets: 1,
    spread: 0.006,
    interval: 0.38,
    reload: 2.1,
    range: 140,
    zoom: 38,
    color: '#a9d0e8',
    loot: 6,
    fp: { len: 0.92, rot: [0, -H, 0] },
    char: 'Sniper_2',
  },
  {
    name: 'THUMPER',
    ru: 'Grenade Launcher',
    model: 'grenadelauncher',
    category: 'power',
    mag: 4,
    reserve: 12,
    damage: 95,
    pellets: 1,
    spread: 0,
    interval: 0.8,
    reload: 2.8,
    range: 90,
    speed: 24,
    gravity: 14,
    radius: 5,
    projectile: 'grenade',
    color: '#9fd36f',
    loot: 3,
    fp: { len: 0.72, rot: [0, -H, 0] },
    char: 'GrenadeLauncher',
  },
  {
    name: 'WHISPER',
    ru: 'Crossbow',
    model: 'crossbow',
    category: 'power',
    mag: 1,
    reserve: 15,
    damage: 82,
    pellets: 1,
    spread: 0,
    interval: 0.3,
    reload: 1.3,
    range: 150,
    speed: 60,
    gravity: 6,
    projectile: 'bolt',
    silent: true,
    color: '#c7b18a',
    loot: 4,
    fp: { len: 0.66, rot: [0, -H, 0] },
    char: 'mount:crossbow',
    iconRot: [0.7, 0, 0],
  },
  {
    name: 'STORM',
    ru: 'Minigun',
    model: 'minigun',
    category: 'power',
    mag: 120,
    reserve: 240,
    damage: 12,
    pellets: 1,
    spread: 0.085,
    interval: 0.055,
    reload: 4.2,
    range: 70,
    spinup: 0.65,
    move: 0.8,
    color: '#f2d06b',
    loot: 2,
    fp: { len: 0.64, rot: [0, -H, 0] },
    char: 'mount:minigun',
  },
  {
    name: 'TALON',
    ru: 'Throwing Dagger',
    model: 'dagger',
    category: 'secondary',
    starter: true,
    mag: 1,
    reserve: 5,
    damage: 70,
    pellets: 1,
    spread: 0,
    interval: 0.35,
    reload: 0.45,
    range: 60,
    speed: 38,
    gravity: 9,
    projectile: 'dagger',
    silent: true,
    color: '#b9c2cc',
    loot: 4,
    fp: { len: 0.32, rot: [-H, 0, 0] },
    char: 'Knife_2',
    iconRot: [0, 0, H],
  },
  {
    name: 'GRENADE',
    ru: 'Hand Grenade',
    model: 'grenadelauncher',
    category: 'power',
    mag: 1,
    reserve: 5,
    damage: 100,
    pellets: 1,
    spread: 0,
    interval: 0.7,
    reload: 0.85,
    range: 42,
    speed: 18,
    gravity: 17,
    radius: 5.5,
    projectile: 'handgrenade',
    fuse: 2.6,
    bounce: 0.48,
    color: '#6f9668',
    loot: 4,
    fp: { len: 0.58, rot: [0, -H, 0] },
    char: 'GrenadeLauncher',
  },
  {
    name: 'C4',
    ru: 'Remote Charge',
    model: 'handcannon',
    category: 'power',
    mag: 1,
    reserve: 3,
    damage: 145,
    pellets: 1,
    spread: 0,
    interval: 0.8,
    reload: 0.9,
    range: 34,
    speed: 12,
    gravity: 16,
    radius: 6.5,
    projectile: 'c4',
    remote: true,
    sticky: true,
    color: '#d5a45c',
    loot: 3,
    fp: { len: 0.34, rot: [0, H, 0] },
    char: 'Revolver_Small',
    iconRot: [0, Math.PI, 0],
  },
];
export const MELEE = WEAPONS.flatMap((w, i) => (w.melee ? [i] : []));
// Loot rarity: damage, reload speed and magazine scale with rarity. Colors are used across the UI and loot beams.
export const RARITIES = [
  { id: 'common', name: 'COMMON', color: '#b9c1c6', damage: 1, reload: 1, mag: 1 },
  { id: 'uncommon', name: 'UNCOMMON', color: '#6fd67a', damage: 1.08, reload: 0.95, mag: 1 },
  { id: 'rare', name: 'RARE', color: '#4fa8ff', damage: 1.16, reload: 0.9, mag: 1.1 },
  { id: 'epic', name: 'EPIC', color: '#b574ff', damage: 1.25, reload: 0.84, mag: 1.2 },
  { id: 'legendary', name: 'LEGENDARY', color: '#ffb23f', damage: 1.35, reload: 0.78, mag: 1.3 },
];
// Special equipment worn on the back. Hold jump in the air to use.
export const GEAR = [
  {
    id: 'jetpack',
    name: 'JETPACK',
    desc: 'Hold jump in the air to fly upward. Refuels on the ground.',
    model: 'jetpack',
    fuel: 100,
    burn: 34,
    refill: 14,
    starter: true,
    color: '#e0823d',
    iconRot: [0, H, 0],
  },
  {
    id: 'glider',
    name: 'GLIDER',
    desc: 'Hold jump while falling to glide far and land softly.',
    model: 'glider',
    starter: true,
    color: '#3f8f86',
    iconRot: [0.35, 0, 0],
  },
];
